version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn deploy-storybook
          name: Deploy Storybook

workflows:
  node-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
      - deploy:
          filters:
            branches:
              only:
                - main
